<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testPackage2.VerifyOrderSubmission" tests="12" time="76.199" ignored="0" failures="0" timestamp="09 Apr 2018 10:18:16 GMT" skipped="2" hostname="EXIND3901" errors="2">
  <testcase name="cmLogin" time="2.298" classname="testPackage2.VerifyOrderSubmission"/>
  <testcase name="address_SiteTechnicalContact" time="8.467" classname="testPackage2.VerifyOrderSubmission"/>
  <testcase name="customerCreation" time="14.808" classname="testPackage2.VerifyOrderSubmission"/>
  <testcase name="accountCreation_Service" time="5.726" classname="testPackage2.VerifyOrderSubmission"/>
  <testcase name="addressCreation" time="13.833" classname="testPackage2.VerifyOrderSubmission"/>
  <testcase name="accountCreation_Billing" time="7.668" classname="testPackage2.VerifyOrderSubmission"/>
  <testcase name="cmLogout" time="0.000" classname="testPackage2.VerifyOrderSubmission">
    <skipped/>
  </testcase> <!-- cmLogout -->
  <testcase name="orderSummary" time="0.002" classname="testPackage2.VerifyOrderSubmission">
    <skipped/>
  </testcase> <!-- orderSummary -->
  <testcase name="accountCreation_PrimaryContact" time="5.493" classname="testPackage2.VerifyOrderSubmission"/>
  <testcase name="serviceConfiguration" time="12.396" classname="testPackage2.VerifyOrderSubmission">
    <error type="java.lang.RuntimeException" message="Unexpected result for screenshot command: null">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: null
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:351)
	at frameworkPackage.FrameworkBase.captureScreen(FrameworkBase.java:311)
	at frameworkPackage.FrameworkBase.extentReportsStep(FrameworkBase.java:334)
	at cmPages.ServicePage.serviceConfiguration(ServicePage.java:102)
	at testPackage2.VerifyOrderSubmission.serviceConfiguration(VerifyOrderSubmission.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- serviceConfiguration -->
  <testcase name="openURL_CM" time="5.508" classname="testPackage2.VerifyOrderSubmission"/>
  <testcase name="endMethod" time="0.000" classname="testPackage2.VerifyOrderSubmission">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentTest.isPathRelative(ExtentTest.java:465)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCapture(ExtentTest.java:275)
	at frameworkPackage.FrameworkBase.extentReportsStep(FrameworkBase.java:347)
	at frameworkPackage.FrameworkBase.endMethod(FrameworkBase.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- endMethod -->
</testsuite> <!-- testPackage2.VerifyOrderSubmission -->
